// 自動生成。直接編集しないこと（node build-precache.mjs で再生成）
self.PRECACHE_VERSION = 'v052cad85984a';
self.PRECACHE_FILES = [
  "./",
  "app.js",
  "games/daily.js",
  "games/deduction.js",
  "games/klondike.js",
  "games/lightsout.js",
  "games/mahjong.js",
  "games/manifest.js",
  "games/memoflip.js",
  "games/merge2048.js",
  "games/minesweeper.js",
  "games/numplace.js",
  "games/slide15.js",
  "games/snake.js",
  "games/spider.js",
  "games/stackdrop.js",
  "icon-192.svg",
  "icon-512.svg",
  "index.html",
  "lib/ads.js",
  "lib/cards.js",
  "lib/daily.js",
  "lib/deduction.js",
  "lib/sudoku.js",
  "manifest.webmanifest",
  "promo-shot.html"
];
